{'exp_name': 'exps/i2cl', 'gpus': ['0', '1'], 'models': ['EleutherAI/gpt-j-6B'], 'datasets': ['agnews', 'sst2'], 'seed': 42, 'run_num': 5, 'run_baseline': True, 'metric': 'acc', 'bs': 2, 'load_in_8bit': True, 'use_cache': True, 'demo_sample_method': 'random', 'add_noise': True, 'noise_scale': 0.001, 'epochs': 100, 'optim': 'adamW', 'grad_bs': 2, 'lr': 0.01, 'wd': 0.001, 'cali_example_method': 'normal', 'layer': 'all', 'tok_pos': 'last', 'inject_method': 'linear', 'inject_pos': 'all', 'init_value': [0.1, 1.0], 'module': ['mlp', 'attn'], 'gen_cv_method': 'context', 'post_fuse_method': 'mean', 'split_demon': True, 'gen_example_method': 'normal', 'shot_per_class': 5, 'val_data_num': 32, 'test_data_num': 500, 'sample_method': 'uniform', 'use_instruction': False, 'add_extra_query': False, 'example_separator': '\n'}
Running EleutherAI/gpt-j-6B on agnews with GPU 0
CUDA memory cleared for GPU 0
Process Process-1:
Traceback (most recent call last):
  File "/home/jiii111/miniconda3/envs/i2cl_env/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/jiii111/miniconda3/envs/i2cl_env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "run_i2cl.py", line 244, in run_task
    main(input_args)
  File "run_i2cl.py", line 25, in main
    utils.init_exp_path(args, args.config['exp_name'])
  File "/home/jiii111/iclTaskVector/I2CL/utils.py", line 38, in init_exp_path
    raise ValueError(f"Experiment {exp_name} already exists! please delete it or change the name!")
ValueError: Experiment exps/i2cl already exists! please delete it or change the name!
Running EleutherAI/gpt-j-6B on sst2 with GPU 1
CUDA memory cleared for GPU 1
Process Process-2:
Traceback (most recent call last):
  File "/home/jiii111/miniconda3/envs/i2cl_env/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/jiii111/miniconda3/envs/i2cl_env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "run_i2cl.py", line 244, in run_task
    main(input_args)
  File "run_i2cl.py", line 25, in main
    utils.init_exp_path(args, args.config['exp_name'])
  File "/home/jiii111/iclTaskVector/I2CL/utils.py", line 38, in init_exp_path
    raise ValueError(f"Experiment {exp_name} already exists! please delete it or change the name!")
ValueError: Experiment exps/i2cl already exists! please delete it or change the name!
All tasks completed.
